deployment:
  tasks:
    - export DEPLOYPATH=/home/user/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -r css/ $DEPLOYPATH
    - /bin/cp -r fonts/ $DEPLOYPATH
    - /bin/cp -r images/ $DEPLOYPATH
    - /bin/cp -r js/ $DEPLOYPATH